server:
  port: 8088
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: false

spring:
  application:
    name: login

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1106
    url: jdbc:mysql://localhost:3306/hr?characterEncoding=utf-8
    username: root

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.dingdang.login.pojo