server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#security:
#  basic:
#    enable: true #开启基于HTTP basic的认证
#  user: #配置用户的账号信息
#    name: itcast
#    password: itcast123
#logging:
#  level:
#    root: debug
#  #    org.springframework.web: DEBUG
#  file: /log/log/my_eureka.log
#  pattern:
#    console: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"
#    file: "%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n"
#logging.level.root=WARN
#logging.level.org.springframework.web=DEBUG
#logging.file=/log/log/my.log
#logging.pattern.console=%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n
#logging.pattern.file=%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n