server:
  port: 8080
#  context-path: /member
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: hr-web

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1106
    url: jdbc:mysql://localhost:3306/hr?characterEncoding=utf-8&allowMultiQueries=true
    username: root

feign:
  httpclient:
    connection-timeout: 30000