server:
  port: 8091 #服务端口
spring:
  application:
    name: check
################################################################
# mysql 属性配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hr?characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 1106

#  jpa:
#    hibernate:
#      #ddl-auto: create #ddl-auto:设为create表示每次都重新建表
#      ddl-auto: update #ddl-auto:设为update表示每次都不会重新建表
#    show-sql: true
################################################################
################################################################
#spring集成Mybatis环境
#pojo别名扫描包
mybatis:
  type-aliases-package: com.dingdang.login.pojo
  mapper-locations: classpath:mapper/*Mapper.xml

################################################################
################################################################
eureka:
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry:  true  #是否从Eureka中获取注册信息，默认为true
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://127.0.0.1:8761/eureka/
    eurekaServerConnectTimeoutSeconds: 60
    eurekaServerReadTimeoutSeconds: 60
  instance:
    prefer-ip-address:  true  #将自己的ip地址注册到Eureka服务中
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port} #指定实例id
    lease-expiration-duration-in-seconds: 30 #续约更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 10 # 续约到期时间（默认90秒）
    leaseRenewalIntervalInSeconds: 10 #心跳时间
  fetch-registry: false
################################################################

################################################################
#logging:
#  level:
#    root: debug
##    org.springframework.web: DEBUG
#  file: /log/log/my_provide.log
#  pattern:
#    console: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"
#    file: "%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n"
################################################################